# Generated by Django 6.1 on 2026-09-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
