# Generated by Django 5.1.4 on 2026-09-10 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_experience_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Pisahkan dengan koma', max_length=255)),
                ('achievement', models.CharField(blank=True, max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
