# Generated by Django 5.1.4 on 2026-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('Organizational', 'Organizational'), ('Leadership', 'Leadership'), ('Teaching', 'Teaching'), ('Competition', 'Competition'), ('Community', 'Community'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
