# Generated by Django 5.1.4 on 2026-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Organizational', 'Organizational'), ('Leadership', 'Leadership'), ('Teaching', 'Teaching'), ('Competition', 'Competition'), ('Community', 'Community'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
